AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  order service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  # MyLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     ContentUri: bobsshop-order-service-layer
  #     CompatibleRuntimes:
  #       - python3.10

  OrderGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["bobsshop_oder_service.orders.aws_lambda_handler.get_handler"]
      # CodeUri: bobsshop_order_service/orders/
      # Handler: aws_lambda_handler.get_handler
      # Runtime: python3.10
      # Architectures:
      #   - x86_64
      Events:
        HttpGetRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /orders
            Method: GET

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1
  # OrderCreateFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: bobsshop_order_service/orders/
  #     Handler: aws_lambda_handler.create_handler
  #     Runtime: python3.10
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HttpPostRequest:
  #         Type: Api
  #         Properties:
  #           Path: /orders
  #           Method: POST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt OrderGetFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt OrderGetFunction.Arn
